### ISSUE TITLE
game crashed(?) problem.

### ISSUE THREAD

**Issue by GS245** [ds5678/ModComponent#23]
game turns off when I press space bar and choose Camp Craft from Radial menu.
Only [mod component] has this problem.  Many modes use mod component. please help.

i used a translator. I hope there is no communication problem.

**Comment by Just1C3-2** [comment]
Not only have this one crash bug,sometimes it break games render,will make it game instant crash when loading into survival mode.
And you cant use this page's newest release in 0.62,i think this page is now abandoned

**Comment by Just1C3-2** [comment]
if you can see me,then try to download 0.61,it works perfectly

**Comment by ds5678** [comment]
https://github.com/dommrogers/ModComponent
